doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/mapping'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
            datetime_functions:
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
                week_day_es: App\DQL\WeekDayEs
